#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), *%w(.. lib)))

require "conf"

parser = Conf::Parser.new

content = <<-EOB
  user  www-data;
  worker_processes  4;

  #error_log  logs/error.log;
  #error_log  logs/error.log  notice;
  #error_log  logs/error.log  info;

  events {
    worker_connections  1024;
  }
EOB

result = parser.parse_with_debug(content)

p result